import{RIFT_LOCAL_BUILD_JOB_FORMAT,RIFT_LOCAL_BUILD_VERSION}from'./local-build-core.js';
import{RiftGitHubClient}from'./github.js';
import{getLocal,listLocal,putLocal,saveCandidate,saveResult}from'./storage.js';
const $=s=>document.querySelector(s),client=new RiftGitHubClient(),worker=new Worker(new URL('./local-build-worker.js',import.meta.url),{type:'module'}),pending=new Map();let latest=null,pollTimer=null,syncing=false;
const ui={token:$('#github-token'),connect:$('#connect'),disconnect:$('#disconnect'),auth:$('#auth-status'),queue:$('#queue-status'),waiting:$('#waiting-count'),completed:$('#completed-count'),historyCount:$('#history-count'),auto:$('#auto-poll'),sync:$('#sync-jobs'),refresh:$('#refresh-history'),target:$('#target-path'),load:$('#load-target'),json:$('#candidate-json'),run:$('#run-build'),build:$('#build-status'),publish:$('#publish-result'),download:$('#download-result'),result:$('#result-card'),title:$('#result-title'),resultStatus:$('#result-status'),stats:$('#stats'),stages:$('#stages'),diagnostics:$('#diagnostics'),history:$('#history'),runtime:$('#runtime-pill'),dialog:$('#message-dialog'),dialogTitle:$('#dialog-title'),dialogMessage:$('#dialog-message'),dialogClose:$('#dialog-close')};
const status=(el,text,kind='neutral')=>{el.textContent=text;el.className=`status ${kind}`},show=(title,msg)=>{ui.dialogTitle.textContent=title;ui.dialogMessage.textContent=String(msg||'');ui.dialog.showModal()};ui.dialogClose.onclick=()=>ui.dialog.close();
worker.onmessage=e=>{const m=e.data||{};if(m.type==='ready'){ui.runtime.textContent=`${m.version} · private H2 on demand`;return}const p=pending.get(m.requestId);if(!p)return;if(m.type==='runtime-loading'){ui.runtime.textContent='Loading private H2 runtime…';return}pending.delete(m.requestId);if(m.type==='result'){ui.runtime.textContent=`${m.publicResult?.building_pipeline_version?'H2 pipeline '+m.publicResult.building_pipeline_version:'H2'} · local`;p.resolve(m)}else p.reject(new Error(m.error||'Local worker failed.'))};
function runWorker(job,program){const githubToken=client.getSessionToken();if(!githubToken)throw new Error('Connect GitHub first so Safari can load the private H2 compiler runtime.');const requestId=crypto.randomUUID();return new Promise((resolve,reject)=>{pending.set(requestId,{resolve,reject});worker.postMessage({type:'build',requestId,job,program,githubToken})})}
const manualJob=program=>({format:RIFT_LOCAL_BUILD_JOB_FORMAT,version:1,job_id:`manual-${new Date().toISOString().replace(/[:.]/g,'-')}`,created_at:Date.now(),target:{path:ui.target.value.trim(),branch:client.config.sourceBranch},candidate:{program},changed_paths:[]});
function render(r){latest=r;ui.result.classList.remove('hidden');ui.title.textContent=r.job_id||'Build result';status(ui.resultStatus,r.ok?'PASS':'FAIL',r.ok?'pass':'fail');const s=r.stats||{},rows=[['Structural cells',s.structuralCells??'—'],['Operations',s.operations??'—'],['Masses',s.masses??'—'],['Floors',s.floors??'—'],['Spaces',s.spaces??s.rooms??'—'],['Portals',s.portals??'—'],['Errors',s.errors??(r.ok?0:'—')],['Warnings',s.warnings??'—'],['Duration',`${r.duration_ms??0} ms`]];ui.stats.innerHTML=rows.map(([a,b])=>`<div class="stat"><span>${a}</span><b>${b}</b></div>`).join('');const stages=r.pipeline?.stages||[];ui.stages.innerHTML=stages.length?stages.map(x=>`<div class="stage ${x.status}"><b>${x.id}</b><small>${x.status} · hard ${x.hardFailures||0} · soft ${x.softIssues||0}</small></div>`).join(''):'<p class="hint">Pipeline stopped before a complete stage snapshot was available.</p>';const d=r.diagnostics||[];ui.diagnostics.innerHTML=d.length?d.map(x=>`<div class="diag ${x.severity||'notice'}"><b>${String(x.severity||'notice').toUpperCase()} · ${x.code||'diagnostic'}</b><br>${x.message||''}</div>`).join(''):'<div class="diag notice">No diagnostics. Candidate is clean.</div>';ui.publish.disabled=!client.connected;ui.download.disabled=false}
async function build(job,program,{publish=false}={}){status(ui.build,'Building locally…','busy');status(ui.queue,'Safari H2 worker busy','busy');try{const res=await runWorker(job,program);await saveCandidate(job.job_id,program,res.artifact,res.publicResult);await saveResult(job.job_id,res.publicResult);await putLocal('jobs',{id:job.job_id,job,savedAt:Date.now()});render(res.publicResult);if(publish&&client.connected)await client.writeJsonFile(client.resultPath(job.job_id),res.publicResult,`Rift Local Builder result: ${job.job_id}`);status(ui.build,res.publicResult.ok?'Local PASS':'Local FAIL',res.publicResult.ok?'pass':'fail');status(ui.queue,publish?'Result returned to private GitHub':'Local build complete',res.publicResult.ok?'pass':'fail');await refreshHistory();return res.publicResult}catch(e){status(ui.build,'Build error','fail');status(ui.queue,'Worker error','fail');show('Local build failed',e?.stack||e?.message||e);throw e}}
async function refreshAuth(){if(!client.connected){status(ui.auth,'Disconnected');return}try{const u=await client.whoAmI();await client.verifyRepositoryAccess();status(ui.auth,`@${u.login}`,'pass')}catch{client.disconnect();status(ui.auth,'Reconnect required','fail')}}
ui.connect.onclick=async()=>{try{status(ui.auth,'Verifying token…','busy');const u=await client.connectWithToken(ui.token.value);ui.token.value='';status(ui.auth,`@${u.login}`,'pass');await syncJobs()}catch(e){status(ui.auth,'Connection failed','fail');show('GitHub connection failed',e?.message||e)}};
ui.disconnect.onclick=()=>{client.disconnect();ui.token.value='';status(ui.auth,'Disconnected');ui.publish.disabled=true};
ui.load.onclick=async()=>{try{const f=await client.readJsonFile(ui.target.value.trim());ui.json.value=JSON.stringify(f.json,null,2);status(ui.build,'Loaded from private GitHub','pass')}catch(e){show('Could not load target',e?.message||e)}};
ui.run.onclick=async()=>{try{const p=JSON.parse(ui.json.value);await build(manualJob(p),p)}catch(e){if(e instanceof SyntaxError)show('Candidate JSON is invalid',e.message)}};
ui.publish.onclick=async()=>{if(!latest)return;try{await client.writeJsonFile(client.resultPath(latest.job_id),latest,`Rift Local Builder result: ${latest.job_id}`);status(ui.queue,'Result returned to private GitHub','pass')}catch(e){show('Could not publish result',e?.message||e)}};
ui.download.onclick=()=>{if(!latest)return;const b=new Blob([`${JSON.stringify(latest,null,2)}\n`],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=`${latest.job_id||'rift-local-result'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
async function syncJobs(){if(syncing||!client.connected)return;syncing=true;status(ui.queue,'Syncing private GitHub…','busy');try{const[jobs,results]=await Promise.all([client.listJson(client.config.jobsDir),client.listJson(client.config.resultsDir)]),done=new Set(results.map(x=>x.name.replace(/\.json$/i,''))),waiting=jobs.filter(x=>!done.has(x.name.replace(/\.json$/i,'')));ui.waiting.textContent=waiting.length;ui.completed.textContent=done.size;for(const row of waiting){const job=(await client.readQueueJson(row.path)).json;if(job.format!==RIFT_LOCAL_BUILD_JOB_FORMAT)continue;let program=job.candidate?.program||null;if(!program&&job.source?.path)program=(await client.readJsonFile(job.source.path)).json;if(!program)throw new Error(`Job '${job.job_id}' has no candidate.program or source.path.`);await build(job,program,{publish:true})}status(ui.queue,waiting.length?'Queue processed':'No waiting jobs','pass')}catch(e){status(ui.queue,'Sync failed','fail');show('GitHub queue error',e?.message||e)}finally{syncing=false}}
async function refreshHistory(){const rows=await listLocal('candidates');ui.historyCount.textContent=rows.length;ui.history.innerHTML=rows.length?rows.slice(0,20).map(r=>`<div class="history-row"><div><b>${r.id}</b><span>${new Date(r.savedAt).toLocaleString()} · ${r.publicResult?.ok?'PASS':'FAIL'}</span></div><button class="secondary" data-id="${r.id}">Load</button></div>`).join(''):'<p class="hint">No local candidates yet.</p>';ui.history.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{const r=await getLocal('candidates',b.dataset.id);if(!r)return;ui.json.value=JSON.stringify(r.program,null,2);render(r.publicResult)})}
ui.sync.onclick=syncJobs;ui.refresh.onclick=refreshHistory;ui.auto.onchange=()=>{clearInterval(pollTimer);pollTimer=null;if(ui.auto.checked)pollTimer=setInterval(()=>{if(document.visibilityState==='visible')syncJobs()},20000)};
(async()=>{ui.runtime.textContent=`${RIFT_LOCAL_BUILD_VERSION} · private H2 on demand`;await refreshAuth();await refreshHistory();if(!crypto?.subtle||!window.Worker||!window.indexedDB){status(ui.build,'Unsupported browser','fail');show('Browser capability missing','Rift Local Builder requires Web Workers, IndexedDB and Web Crypto.')}})();
