export const DEFAULT_GITHUB_CONFIG=Object.freeze({owner:'Arctic403',repo:'RiftCityV1',sourceBranch:'ai-static-world-builder',queueBranch:'rift-local-queue',jobsDir:'rift-local-jobs',resultsDir:'rift-local-results'});
const API='https://api.github.com',SESSION_TOKEN_KEY='rift-local-builder.github-token',LOCAL_TOKEN_KEY='rift-local-builder.github-token.persisted';
const enc=p=>String(p).split('/').map(encodeURIComponent).join('/');
const clean=v=>String(v||'').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,180);
const readStorage=(storage,key)=>{try{return storage?.getItem(key)||''}catch{return''}};
const writeStorage=(storage,key,value)=>{try{storage?.setItem(key,String(value));return true}catch{return false}};
const removeStorage=(storage,key)=>{try{storage?.removeItem(key)}catch{}};
function utf8ToBase64(text){const bytes=new TextEncoder().encode(String(text));let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function base64ToUtf8(value){const binary=atob(String(value||'').replace(/\n/g,''));return new TextDecoder().decode(Uint8Array.from(binary,c=>c.charCodeAt(0)))}
async function parsed(r){const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok){const e=new Error(body?.message||body?.error||`GitHub request failed with HTTP ${r.status}.`);e.status=r.status;e.body=body;throw e}return body}
export class RiftGitHubClient{constructor(config=DEFAULT_GITHUB_CONFIG){this.config={...DEFAULT_GITHUB_CONFIG,...config};const sessionToken=readStorage(sessionStorage,SESSION_TOKEN_KEY),persistentToken=readStorage(localStorage,LOCAL_TOKEN_KEY);this.token=sessionToken||persistentToken||'';if(this.token&&!sessionToken)writeStorage(sessionStorage,SESSION_TOKEN_KEY,this.token)}get connected(){return Boolean(this.token)}getSessionToken(){return this.token}get rememberedOnDevice(){return Boolean(readStorage(localStorage,LOCAL_TOKEN_KEY))}disconnect(){this.token='';removeStorage(sessionStorage,SESSION_TOKEN_KEY);removeStorage(localStorage,LOCAL_TOKEN_KEY)}async connectWithToken(token){const t=String(token||'').trim();if(!t)throw new Error('A fine-grained GitHub token is required.');this.token=t;try{const user=await this.whoAmI();await this.verifyRepositoryAccess();writeStorage(sessionStorage,SESSION_TOKEN_KEY,t);if(!writeStorage(localStorage,LOCAL_TOKEN_KEY,t))throw new Error('Safari could not save the GitHub token on this device. Check browser storage/privacy settings.');return user}catch(e){this.disconnect();throw e}}async api(path,{method='GET',body=null}={}){if(!this.token)throw new Error('Connect GitHub first.');return parsed(await fetch(`${API}${path}`,{method,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${this.token}`,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}))}whoAmI(){return this.api('/user')}verifyRepositoryAccess(){return this.api(`/repos/${encodeURIComponent(this.config.owner)}/${encodeURIComponent(this.config.repo)}`)}contentPath(path){return `/repos/${encodeURIComponent(this.config.owner)}/${encodeURIComponent(this.config.repo)}/contents/${enc(path)}`}async listJson(dir,ref=this.config.queueBranch){try{const rows=await this.api(`${this.contentPath(dir)}?ref=${encodeURIComponent(ref)}`);return(Array.isArray(rows)?rows:[]).filter(x=>x.type==='file'&&x.name.endsWith('.json'))}catch(e){if(e.status===404)return[];throw e}}async readJsonFile(path,ref=this.config.sourceBranch){const row=await this.api(`${this.contentPath(path)}?ref=${encodeURIComponent(ref)}`);if(!row?.content)throw new Error(`GitHub did not return inline content for '${path}'.`);return{json:JSON.parse(base64ToUtf8(row.content)),sha:row.sha,path:row.path,ref}}resultPath(jobId){return `${this.config.resultsDir}/${clean(jobId)}.json`}async writeJsonFile(path,payload,message,ref=this.config.queueBranch){let sha=null;try{sha=(await this.api(`${this.contentPath(path)}?ref=${encodeURIComponent(ref)}`))?.sha||null}catch(e){if(e.status!==404)throw e}return this.api(this.contentPath(path),{method:'PUT',body:{message:String(message||`Rift Local Builder: ${path}`),content:utf8ToBase64(`${JSON.stringify(payload,null,2)}\n`),branch:ref,...(sha?{sha}:{})}})}readQueueJson(path){return this.readJsonFile(path,this.config.queueBranch)}}
