const API='https://api.github.com';
const OWNER='Arctic403',REPO='RiftCityV1',BRANCH='ai-static-world-builder';
const FILES={compiler:'public/rift-building-compiler.js',pipeline:'public/rift-building-pipeline.js',interiorArchitecture:'public/rift-interior-architecture.js',interiorPipeline:'public/rift-interior-pipeline.js',material:'public/rift-material-library.js',world:'public/rift-world-coordinates.js'};
let cache=null;
const enc=p=>String(p).split('/').map(encodeURIComponent).join('/');
async function getText(path,token){const r=await fetch(`${API}/repos/${OWNER}/${REPO}/contents/${enc(path)}?ref=${encodeURIComponent(BRANCH)}`,{headers:{Accept:'application/vnd.github.raw+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok){let m=`HTTP ${r.status}`;try{m=(await r.json()).message||m}catch{}throw new Error(`Could not load private H2 runtime '${path}': ${m}`)}return r.text()}
const blobUrl=source=>URL.createObjectURL(new Blob([source],{type:'text/javascript'}));
function swap(source,spec,url){return source.replaceAll(`'${spec}'`,`'${url}'`).replaceAll(`"${spec}"`,`"${url}"`)}
export async function loadPrivateH2Runtime(token){if(cache)return cache;if(!token)throw new Error('GitHub session token is required to load the private H2 runtime.');const[pipelineSrc,interiorPipelineSrc,materialSrc,worldSrc,interiorArchitectureSrc,compilerSrc]=await Promise.all([getText(FILES.pipeline,token),getText(FILES.interiorPipeline,token),getText(FILES.material,token),getText(FILES.world,token),getText(FILES.interiorArchitecture,token),getText(FILES.compiler,token)]);const u={};u.pipeline=blobUrl(pipelineSrc);u.interiorPipeline=blobUrl(interiorPipelineSrc);u.material=blobUrl(materialSrc);u.world=blobUrl(worldSrc);let ia=swap(interiorArchitectureSrc,'./rift-interior-pipeline.js',u.interiorPipeline);u.interiorArchitecture=blobUrl(ia);let c=compilerSrc;c=swap(c,'./rift-material-library.js',u.material);c=swap(c,'./rift-world-coordinates.js',u.world);c=swap(c,'./rift-interior-architecture.js',u.interiorArchitecture);c=swap(c,'./rift-building-pipeline.js',u.pipeline);u.compiler=blobUrl(c);const mod=await import(u.compiler);if(typeof mod.compileRiftBuildingProgram!=='function')throw new Error('Private H2 compiler did not expose compileRiftBuildingProgram().');cache={module:mod,urls:u,source:{owner:OWNER,repo:REPO,branch:BRANCH}};return cache}
